version: '3.4'

services:
  dev:
    container_name: nestjs_api_dev
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run dev:test
    ports:
      - "3333:3333"
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  prod:
    container_name: nestjs_api_prod
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - "3000:3000"
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  nesjs-network: